server:
    port: 12345
    tomcat.uri-encoding: UTF-8
    servlet:
        context-path: /

spring:
    thymeleaf:
        enabled: true
        mode: HTML5
        encoding: UTF-8
        servlet:
            content-type: text/html
        cache: false
        prefix: classpath:/templates/
        check-template: true
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/mercury?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
#    jpa:
#        hibernate:
#            ddl-auto: update
#        show-sql: true

input:
    host: 127.0.0.1
    port: 12333

socketServer:
    host: 0.0.0.0
    port: 9998
    timeout: 30

redis:
    host: 127.0.0.1
    port: 6379
    pwd:
    max-wait: 30000
    max-active: 100
    max-idle: 20
    min-idle: 0
    timeout: 3000